### ISSUE TITLE
Elixir.ready is not a function

### ISSUE THREAD

**Issue by stevepop** [JeffreyWay/Laravel-Elixir-v6-Vue-example#1]
Hi Jeffrey,

I cloned this repository and followed the instructions to install webpack as well as other dependencies. However when I ran gulp I got the following error;

```
/Users/steve/devapps/sites/sandbox/Laravel-Elixir-v6-Vue-example/node_modules/laravel-elixir-vue/main.js:3
Elixir.ready(() => {
       ^

TypeError: Elixir.ready is not a function
    at Object.<anonymous> (/Users/steve/devapps/sites/sandbox/Laravel-Elixir-v6-Vue-example/node_modules/laravel-elixir-vue/main.js:3:8)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/steve/devapps/sites/sandbox/Laravel-Elixir-v6-Vue-example/gulpfile.js:3:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

I am wondering what the problem could be?

Thanks

Steve

**Comment by stevepop** [comment]
Okay I changed the version of Elixir to 6.0.0-9 in package.json and now the error has changed to the one below;

```
/Users/steve/devapps/sites/sandbox/Laravel-Elixir-v6-Vue-example/node_modules/laravel-elixir-vue/main.js:4
    Elixir.config.js.webpack.loaders.push({
                            ^

TypeError: Cannot read property 'loaders' of undefined
    at /Users/steve/devapps/sites/sandbox/Laravel-Elixir-v6-Vue-example/node_modules/laravel-elixir-vue/main.js:4:29
    at /Users/steve/devapps/sites/sandbox/Laravel-Elixir-v6-Vue-example/node_modules/laravel-elixir/dist/index.js:29:16
    at Array.forEach (native)
    at global.Elixir (/Users/steve/devapps/sites/sandbox/Laravel-Elixir-v6-Vue-example/node_modules/laravel-elixir/dist/index.js:28:24)
    at Object.<anonymous> (/Users/steve/devapps/sites/sandbox/Laravel-Elixir-v6-Vue-example/gulpfile.js:16:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

**Comment by JeffreyWay** [comment]
That's because you're referencing the Elixir webpack extension before installing the main webpack extension. Add this:

npm install laravel-elixir-webpack-official --save-dev
